version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/django-docker
    ports:
      - "8990:8990"
    depends_on:
      - db
    command:
      - ./docker-entrypoint.sh