# Generated by Django 2.2.6 on 2019-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='productslist',
            field=models.ManyToManyField(blank=True, to='marketplace.Product'),
        ),
    ]
